import { useState } from 'react';
import { markdownToHtml, markdownToStyledHtmlDoc } from '../utils/markdown';
import { api } from '../api';

interface ReportViewerProps {
  report: string;
  projectTitle: string;
  projectId: string;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 2000);
}

function slugify(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export default function ReportViewer({ report, projectTitle, projectId }: ReportViewerProps) {
  const [docxLoading, setDocxLoading] = useState(false);
  const [docxError, setDocxError] = useState<string | null>(null);
  const slug = slugify(projectTitle);

  const handleDownloadHtml = () => {
    const html = markdownToStyledHtmlDoc(report, `${projectTitle} — Feasibility Report`);
    triggerDownload(new Blob([html], { type: 'application/octet-stream' }), `${slug}-feasibility.html`);
  };

  const handleDownloadDocx = async () => {
    setDocxLoading(true);
    setDocxError(null);
    try {
      const blob = await api.feasibility.exportToDocx(projectId);
      triggerDownload(blob, `${slug}-feasibility.docx`);
    } catch (e: any) {
      setDocxError(e.message || 'Word export failed');
    } finally {
      setDocxLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-100">Feasibility Report</h2>
        <div className="flex gap-2">
          <button
            onClick={handleDownloadHtml}
            className="px-3 py-1.5 text-sm bg-gray-700 hover:bg-gray-600 text-gray-200 rounded transition-colors"
          >
            Download HTML
          </button>
          <button
            onClick={handleDownloadDocx}
            disabled={docxLoading}
            className="px-3 py-1.5 text-sm bg-blue-700 hover:bg-blue-600 disabled:opacity-50 text-white rounded transition-colors"
          >
            {docxLoading ? 'Preparing…' : 'Download Word'}
          </button>
        </div>
      </div>

      {docxError && (
        <div className="p-3 bg-red-900/40 border border-red-800 rounded text-red-300 text-sm">
          Word export failed: {docxError}
        </div>
      )}

      <div className="bg-gray-900 rounded-lg border border-gray-800 p-6">
        <div
          className="markdown-content"
          dangerouslySetInnerHTML={{ __html: markdownToHtml(report) }}
        />
        <hr className="border-gray-700 mt-8 mb-4" />
        <p className="text-xs text-gray-500 leading-relaxed">
          <strong className="text-gray-400">Disclaimer:</strong> This report was generated by PatentForge, an AI-powered research and preparation tool. It does not constitute legal advice, a patent opinion, or attorney services. All findings should be independently verified by a registered patent attorney or patent agent. Always consult qualified legal counsel before making patent filing decisions.
        </p>
      </div>
    </div>
  );
}
