import { useState, useMemo } from 'react';
import { markdownToStyledHtmlDoc } from '../utils/markdown';
import { api } from '../api';

interface ReportViewerProps {
  report: string;
  preRenderedHtml?: string;
  projectTitle: string;
  projectId: string;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 2000);
}

function slugify(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

const REPORT_CSS = `
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: #030712; color: #f3f4f6;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 15px; line-height: 1.7; padding: 2rem; max-width: 900px; margin: 0 auto;
}
h1 { font-size: 1.75rem; font-weight: 700; color: #60a5fa; border-bottom: 1px solid #374151; padding-bottom: 0.5rem; margin: 1.5rem 0 0.75rem; }
h2 { font-size: 1.4rem; font-weight: 600; color: #93c5fd; border-bottom: 1px solid #1f2937; padding-bottom: 0.25rem; margin: 1.25rem 0 0.5rem; }
h3 { font-size: 1.2rem; font-weight: 600; color: #c4b5fd; margin: 1rem 0 0.5rem; }
h4 { font-size: 1rem; font-weight: 600; color: #e5e7eb; margin: 0.75rem 0 0.25rem; }
p { color: #d1d5db; margin: 0.5rem 0; }
ul { list-style: disc; margin: 0.5rem 0 0.5rem 1.5rem; color: #d1d5db; }
ol { list-style: decimal; margin: 0.5rem 0 0.5rem 1.5rem; color: #d1d5db; }
li { margin-bottom: 0.25rem; }
table { width: 100%; border-collapse: collapse; font-size: 0.875rem; margin: 1rem 0; }
th { background: #1f2937; color: #93c5fd; font-weight: 600; padding: 0.5rem 0.75rem; text-align: left; border: 1px solid #374151; }
td { padding: 0.5rem 0.75rem; border: 1px solid #1f2937; color: #d1d5db; }
tr:nth-child(even) td { background: #111827; }
code { background: #1f2937; color: #93c5fd; padding: 0.1rem 0.35rem; border-radius: 4px; font-size: 0.85em; font-family: 'Courier New', monospace; }
pre { background: #1f2937; border-radius: 6px; padding: 1rem; overflow-x: auto; margin: 0.75rem 0; }
pre code { background: transparent; padding: 0; color: #d1d5db; }
hr { border: none; border-top: 1px solid #374151; margin: 1.25rem 0; }
strong { color: #f9fafb; font-weight: 600; }
em { color: #9ca3af; font-style: italic; }
blockquote { border-left: 4px solid #3b82f6; padding: 0.5rem 1rem; background: rgba(31,41,55,0.5); margin: 0.75rem 0; color: #9ca3af; font-style: italic; }
a { color: #60a5fa; text-decoration: underline; }
a:hover { color: #93c5fd; }
`.trim();

const DISCLAIMER = `<hr style="margin-top:3rem"><p style="font-size:0.8rem;color:#6b7280;line-height:1.5;margin-top:1rem"><strong style="color:#9ca3af">Disclaimer:</strong> This report was generated by PatentForge, an open-source AI-powered patent landscape research tool. It is intended for informational and educational purposes only. This report does not constitute legal advice. No attorney-client relationship is created by this report. Before making any filing, licensing, enforcement, or investment decisions based on this report, consult a registered patent attorney.</p>`;

export default function ReportViewer({ report, preRenderedHtml, projectTitle, projectId }: ReportViewerProps) {
  const [docxLoading, setDocxLoading] = useState(false);
  const [docxError, setDocxError] = useState<string | null>(null);
  const slug = slugify(projectTitle);

  // Build a complete HTML document for the iframe — use server-rendered HTML if available
  const htmlBlobUrl = useMemo(() => {
    const bodyHtml = preRenderedHtml ?? '';
    const doc = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>${REPORT_CSS}</style></head><body>${bodyHtml}${DISCLAIMER}</body></html>`;
    const blob = new Blob([doc], { type: 'text/html' });
    return URL.createObjectURL(blob);
  }, [preRenderedHtml]);

  const handleDownloadHtml = () => {
    const html = markdownToStyledHtmlDoc(report, `${projectTitle} — Feasibility Report`);
    triggerDownload(new Blob([html], { type: 'application/octet-stream' }), `${slug}-feasibility.html`);
  };

  const handleDownloadDocx = async () => {
    setDocxLoading(true);
    setDocxError(null);
    try {
      const blob = await api.feasibility.exportToDocx(projectId);
      triggerDownload(blob, `${slug}-feasibility.docx`);
    } catch (e: any) {
      setDocxError(e.message || 'Word export failed');
    } finally {
      setDocxLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-100">Feasibility Report</h2>
        <div className="flex gap-2">
          <button
            onClick={handleDownloadHtml}
            className="px-3 py-1.5 text-sm bg-gray-700 hover:bg-gray-600 text-gray-200 rounded transition-colors"
          >
            Download HTML
          </button>
          <button
            onClick={handleDownloadDocx}
            disabled={docxLoading}
            className="px-3 py-1.5 text-sm bg-blue-700 hover:bg-blue-600 disabled:opacity-50 text-white rounded transition-colors"
          >
            {docxLoading ? 'Preparing...' : 'Download Word'}
          </button>
        </div>
      </div>

      {docxError && (
        <div className="p-3 bg-red-900/40 border border-red-800 rounded text-red-300 text-sm">
          Word export failed: {docxError}
        </div>
      )}

      <iframe
        src={htmlBlobUrl}
        title="Feasibility Report"
        className="w-full rounded-lg border border-gray-800"
        style={{ height: 'calc(100vh - 200px)', minHeight: '600px', background: '#030712' }}
        sandbox="allow-same-origin"
      />
    </div>
  );
}
