"""
Export patent application to DOCX and Markdown formats.
"""

from __future__ import annotations
import io
from datetime import datetime

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

from .models import ExportRequest


def export_docx(req: ExportRequest) -> bytes:
    """Generate a Word document from the application sections."""
    doc = Document()

    # Title page
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(req.title or "Patent Application")
    run.bold = True
    run.font.size = Pt(18)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run("Patent Application")
    sub_run.font.size = Pt(14)

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d')}")

    # Disclaimer
    disclaimer = doc.add_paragraph()
    disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    d_run = disclaimer.add_run(
        "\nIMPORTANT: This is an AI-generated research draft. "
        "It must be reviewed by a registered patent attorney before filing."
    )
    d_run.italic = True
    d_run.font.size = Pt(9)

    doc.add_page_break()

    # Sections
    sections = [
        ("Cross-Reference to Related Applications", req.cross_references),
        ("Background of the Invention", req.background),
        ("Summary of the Invention", req.summary),
        ("Detailed Description of Preferred Embodiments", req.detailed_description),
        ("Claims", req.claims),
        ("Abstract of the Disclosure", req.abstract),
        ("Brief Description of the Drawings", req.figure_descriptions),
        ("Information Disclosure Statement", req.ids_table),
    ]

    for heading, content in sections:
        if not content or not content.strip():
            continue
        doc.add_heading(heading, level=1)
        for para_text in content.split("\n\n"):
            para_text = para_text.strip()
            if not para_text:
                continue
            if para_text.startswith("|"):
                doc.add_paragraph(para_text, style="Normal")
            else:
                doc.add_paragraph(para_text)

    # Footer disclaimer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    f_run = footer.add_run("Generated by PatentForge — Not Legal Advice")
    f_run.italic = True
    f_run.font.size = Pt(8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_markdown(req: ExportRequest) -> str:
    """Generate a Markdown document from the application sections."""
    parts = []

    parts.append(f"# {req.title or 'Patent Application'}\n")
    parts.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d')}*\n")
    parts.append("*AI-generated research draft — must be reviewed by a registered patent attorney.*\n")

    sections = [
        ("Cross-Reference to Related Applications", req.cross_references),
        ("Background of the Invention", req.background),
        ("Summary of the Invention", req.summary),
        ("Detailed Description of Preferred Embodiments", req.detailed_description),
        ("Claims", req.claims),
        ("Abstract of the Disclosure", req.abstract),
        ("Brief Description of the Drawings", req.figure_descriptions),
        ("Information Disclosure Statement", req.ids_table),
    ]

    for heading, content in sections:
        if not content or not content.strip():
            continue
        parts.append(f"\n## {heading}\n")
        parts.append(content.strip())
        parts.append("")

    return "\n".join(parts)
